// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMessage = `-- name: CreateMessage :exec
insert into kafka_outbox(event, entity_type, entity_id, data)
values
    ($1,$2, $3, $4)
`

type CreateMessageParams struct {
	Event      pgtype.Text
	EntityType pgtype.Text
	EntityID   pgtype.Text
	Data       pgtype.Text
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) error {
	_, err := q.db.Exec(ctx, createMessage,
		arg.Event,
		arg.EntityType,
		arg.EntityID,
		arg.Data,
	)
	return err
}
